### ISSUE TITLE
Issue with timeseries: datetime.datetime() is not JSON serializable

### ISSUE THREAD

**Issue by cheremovsky** [chartit/django-chartit#31] opened 2015-04-11 15:30 UTC
I try to plot a timeseries and have datetime entries in my DB. Looks like I cannot just plot a timeseries.

**Comment by N3TC4T** [comment] 2016-04-09 09:07
+1

**Comment by atodorov** [comment] 2016-07-28 12:07
This is a duplicate of https://github.com/chartit/django-chartit/issues/2

**Closed by atodorov** 2016-07-28 12:07 UTC
