### ISSUE TITLE
Generate Charts from Views?

### ISSUE THREAD

**Issue by Cosbgn** [chartit/django-chartit#50] opened 2017-03-30 13:00 UTC
I'm going through the documentation but I'm a bit confused on one thing. On all the examples charts are generated from data on models. 

I'm using an API (in my `views.py`) to retrieve data and I would like to generate charts on the fly without the need to save this data to my db. Is this possible? Any example that uses data from the views?

Thanks

**Comment by Cosbgn** [comment] 2017-03-30 13:10
Hi @atodorov thanks for the quick response. So for example one chart I would like to have is a simple line chart with sessions (Y-axis) and date (X-axis). The API gives me data back in this format: https://gist.github.com/Cosbgn/526f5fd7150c4065b9fa4e54909ebb78

My first approach is to have several functions in my `views.py` file that get the data and then return the template loading multiple charts, but maybe I'm doing things wrong. Should I save this in my db? I wanted to avoid that because I'm dealing with a lot of data for each user and I might overcomplicate things.  Thanks

**Comment by Cosbgn** [comment] 2017-03-30 20:57
I concluded that the best way is to save data in my db and use that to load charts. Thanks.

**Comment by atodorov** [comment] 2017-03-31 07:39
Duplicate of #21. Not possible at the moment. I've been planning to work on it for quite a while but haven't managed to find the time. Feel free to open a PR or pm me if you'd like this to happen sooner.

**Closed by atodorov** 2017-03-31 07:39 UTC
